sudo: required
dist: trusty

language: node_js
node_js:
  - "12"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install: 
  - npm install
script:
  - ng test angular-toaster --watch=false --code-coverage
after_script:
  - "cat ./coverage/angular-toaster/lcov.info | ./node_modules/coveralls/bin/coveralls.js"