name: Angular Ci

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  HUSKY: 0

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install package
        run: npm ci
      - name: Build
        run: npm run build
      - name: Lint check
        run: npm run lint
      - name: Schematics check
        run: npm run test:schematics
      - name: Unit Test
        run: npm run test:lib:ci || true
